import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLUGIN_ID = "gay-toolbar";
const INSTALL_FILES = ["main.js", "styles.css", "manifest.json"];

/**
 * Resolve the Obsidian install dir to overwrite on each build.
 * Override with OBSIDIAN_PLUGIN_DIR or env.mjs `obsidianExportPath`.
 */
async function resolveObsidianOutDir() {
  if (process.env.OBSIDIAN_PLUGIN_DIR) {
    return path.resolve(process.env.OBSIDIAN_PLUGIN_DIR);
  }
  try {
    const env = await import("./env.mjs");
    if (env.obsidianExportPath) {
      return path.resolve(env.obsidianExportPath);
    }
  } catch {
    // env.mjs is optional
  }
  return path.resolve(__dirname, `../../../.obsidian/plugins/${PLUGIN_ID}`);
}

function buildCSS() {
  const stylesDir = "./styles";
  const cssFiles = fs
    .readdirSync(stylesDir)
    .filter((file) => file.endsWith(".css"))
    .map((file) => path.join(stylesDir, file))
    .sort();

  let combinedCSS = "";
  cssFiles.forEach((file) => {
    if (fs.existsSync(file)) {
      combinedCSS += fs.readFileSync(file, "utf8") + "\n";
    }
  });

  fs.writeFileSync("./styles.css", combinedCSS);
  console.log(`CSS compiled successfully! (${cssFiles.length} files)`);
}

function copyToObsidian(outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  for (const file of INSTALL_FILES) {
    const src = path.resolve(__dirname, file);
    if (!fs.existsSync(src)) continue;
    fs.copyFileSync(src, path.join(outDir, file));
  }
  console.log(`Copied ${INSTALL_FILES.join(", ")} → ${outDir}`);
}

const outDir = await resolveObsidianOutDir();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.tsx"],
  loader: {
    ".png": "dataurl",
  },
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  minify: prod,
  define: prod ? { "process.env.NODE_ENV": '"production"' } : undefined,
  treeShaking: true,
  outdir: ".",
  entryNames: "[name]",
  plugins: [
    {
      name: "copy-to-obsidian",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length > 0) return;
          copyToObsidian(outDir);
        });
      },
    },
  ],
});

buildCSS();

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();

  const chokidar = await import("chokidar");

  const watcher = chokidar.watch("./styles", {
    ignored: /(^|[\/\\])\../,
    persistent: true,
    ignoreInitial: true,
  });

  watcher.on("change", (changedPath) => {
    if (changedPath.endsWith(".css")) {
      console.log(`CSS file changed: ${changedPath}`);
      buildCSS();
      copyToObsidian(outDir);
    }
  });

  watcher.on("add", (changedPath) => {
    if (changedPath.endsWith(".css")) {
      console.log(`CSS file added: ${changedPath}`);
      buildCSS();
      copyToObsidian(outDir);
    }
  });

  watcher.on("error", (error) => {
    console.error("CSS watcher error:", error);
  });

  console.log(`CSS watcher started; install dir: ${outDir}`);
}
